
#### production
NAME: 'ecog'
DATASET:
  SPEC_CHANS: 64
  TEMPORAL_SAMPLES: 128
  BCTS: True
  MAX_RESOLUTION_LEVEL: 7
  SELECTREGION: []
  BLOCKREGION: []
  SUBJECT: ['NY869' ]
  PROD: True
  FAKE_REPROD: False
  PRE_ARTICULATE: False 
  TRIM: True
MODEL:
  N_FORMANTS: 6
  N_FORMANTS_NOISE: 1
  N_FORMANTS_ECOG: 6
  WAVE_BASED : True
  DO_MEL_GUIDE : False 
  BGNOISE_FROMDATA: True
  N_FFT : 512
  NOISE_DB : -50
  MAX_DB : 22.5 
  NOISE_DB_AMP : -25
  MAX_DB_AMP : 14
  POWER_SYNTH: True
  NORMED_MASK: False
  DUMMY_FORMANT: True
  LEARNED_MASK: True
  N_FILTER_SAMPLES: 80
  DYNAMIC_FILTER_SHAPE: False
  LEARNEDBANDWIDTH: False
  CAUSAL: False
  ANTICAUSAL: False
  LESS_TEMPORAL_FEATURE: True
  LATENT_SPACE_SIZE: 128
  LAYER_COUNT: 6
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 16
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
  TRUNCATIOM_CUTOFF: 5
  CHANNELS: 1
  UNIQ_WORDS: 50
  MAPPING_FROM_ECOG: "ECoGMappingBottleneck"
  ECOG: False #will be overloaded if FINETUNE
  SUPLOSS_ON_ECOGF: False # will be overloaded to FIX_GEN if FINETUNE,spec supervise loss only apply to ecog encoder
  W_SUP: False
  GAN: True
  GENERATOR: "GeneratorFormant"
  ENCODER: "EncoderFormant"
  ECOG_COMPUTE_DB_LOUDNESS: True
  AVERAGE_W: True
  TEMPORAL_W: True
  GLOBAL_W: True
  TEMPORAL_GLOBAL_CAT: True
  RESIDUAL: True
  W_CLASSIFIER: False
  CYCLE: False
  ATTENTIONAL_STYLE: True
  #T            4      8      16    32    64    128 
  ATTENTION: [False, False, False, False, False, False]
  HEADS: 1
  APPLY_PPL: False 
  APPLY_PPL_D: False
  PPL_WEIGHT: 100
  PPL_GLOBAL_WEIGHT: 0
  PPLD_WEIGHT: 1
  PPLD_GLOBAL_WEIGHT: 0
  COMMON_Z: True
  mapping_layers: 0
  single_patient_mapping: -1
  region_index: 0
  multiscale: 0
  rdropout: 0
  TRANSFORMER:
    HIDDEN_DIM : 256
    DIM_FEEDFORWARD : 256
    ENCODER_ONLY : True
    ATTENTIONAL_MASK : False
    N_HEADS : 8
    NON_LOCAL: False
  OUTPUT_DIR: ''
IGNORE_LOADING: False
LOAD_DIR: '' 
FINETUNE:
  FINETUNE: True 
  FIX_GEN: True
  ENCODER_GUIDE: True
  SPECSUP: True
  APPLY_FLOODING: True

VISUAL:
  VISUAL: False
  WEIGHTED_VIS: False
  KEY: 'freq_formants_hamon'
  INDEX: [0]
  A2A: False
#####################################

TRAIN:
  PROGRESSIVE: False
  W_WEIGHT: 1
  CYCLE_WEIGHT: 1
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 16
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: [96]
  TRAIN_EPOCHS: 60
  #                    4    8   16    32    64    128    256
  LOD_2_BATCH_8GPU: [512, 256, 128,   64,   32,    32] # If GPU memory ~16GB reduce last number from 32 to 24
  LOD_2_BATCH_4GPU: [64, 64, 64,   64,   32,    16]
  LOD_2_BATCH_2GPU: [64, 64, 64,   64,   32,    16]
  LOD_2_BATCH_1GPU: [64, 64, 64,   64,   32,    16]
  BATCH_SIZE : 32
  LEARNING_RATES: [0.0015,  0.0015,   0.0015,    0.002,     0.003,    0.003]